import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {} from "next/font/google";
import { Toaster } from "react-hot-toast";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const sourGummy = localFont({
  src: "./fonts/SourGummy-VariableFont_wdth,wght.ttf",
  variable: "--sour-gummy",
  weight: "100 900",
});

const baloo = localFont({
  src: "./fonts/Baloo2-VariableFont_wght.ttf",
  variable: "--baloo",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${sourGummy.variable} ${baloo.variable}  antialiased`}>
        {children}
        <Toaster
          position="bottom-right"
          reverseOrder={false}
          // toastOptions={{
          //   style: {
          //     backgroundColor: "#1f2937", // Secondary (gray-800)
          //     color: "#ef4444", // Red text
          //     padding: "15px 4rem",
          //     borderRadius: "0.375rem", // Rounded-md
          //     boxShadow: "0px 4px 6px rgba(0, 0, 0, 0.1)", // Tailwind shadow-lg
          //   },
          //   success: {
          //     style: {
          //       backgroundColor: "#000000", // Black
          //       color: "#ffffff", // White
          //     },
          //   },
          //   error: {
          //     style: {
          //       backgroundColor: "#f87171", // Red-500
          //       color: "#ffffff", // White
          //     },
          //   },
          // }}
        />
      </body>
    </html>
  );
}
